import os

from snakebids import bids, generate_inputs, set_bids_spec
import snakebids

# update v15 spec to add template entity
spec = snakebids.paths.specs.v0_15_0()
tpl_spec = spec[0].copy()
tpl_spec["entity"] = "template"
tpl_spec["tag"] = "tpl"
spec.insert(0, tpl_spec)
set_bids_spec(spec)


configfile: os.path.join(workflow.basedir, "..", "config", "snakebids.yml")


root = os.path.expandvars(config["output_dir"])
target_template = config.get("target_template", "ABAv3")


inputs = generate_inputs(
    bids_dir=config["bids_dir"],
    pybids_inputs=config["pybids_inputs"],
    pybidsdb_dir=config.get("pybidsdb_dir"),
    pybidsdb_reset=config.get("pybidsdb_reset"),
    derivatives=config.get("derivatives", None),
    participant_label=config.get("participant_label", None),
    exclude_participant_label=config.get("exclude_participant_label", None),
    validate=not config.get("plugins.validator.skip", False),
)


if "mri" in inputs:
    suffixes = inputs["mri"].entities["suffix"]
    if len(suffixes) == 1:
        mri_suffix = suffixes[0]
    else:
        raise ValueError(
            f"More than one MRI suffix found, use --filter-mri to narrow your search: {suffixes}"
        )
else:
    mri_suffix = "T2starw"


rule all:
    input:
        # preproc outputs (desc-preproc feeds into register_to_mean)
        inputs["mri"].expand(
            bids(
                root=root,
                datatype="anat",
                desc="preproc",
                suffix=f"{mri_suffix}.nii.gz",
                **inputs.subj_wildcards,
            )
        ),
        # atlas outputs
        os.path.join(root, "mri-atlas", "mri-atlas.nii.gz"),
        os.path.join(root, "mri-atlas", f"from-mriatlas_to-{target_template}_0GenericAffine.mat"),
        os.path.join(root, "mri-atlas", f"from-mriatlas_to-{target_template}_1Warp.nii.gz"),
        os.path.join(root, "mri-atlas", f"from-mriatlas_to-{target_template}_1InverseWarp.nii.gz"),
        inputs["mri"].expand(
            bids(
                root=root,
                datatype="anat",
                space=target_template,
                desc="deformwarped",
                suffix=f"{mri_suffix}.nii.gz",
                **inputs.subj_wildcards,
            )
        ),


include: "rules/common.smk"
include: "rules/import.smk"
include: "rules/preproc_mri.smk"
include: "rules/mri_space_atlas.smk"
